### ISSUE TITLE
Upstart doesn't properly set user

### ISSUE THREAD

**Issue by EvanKrall** [EvanKrall/puppet-initscript#7]
For some reason the upstart template simply sets environment variables for user/group: https://github.com/EvanKrall/puppet-initscript/blob/master/templates/upstart.erb#L9. I think this is a holdover from using sudo/start-stop-daemon to set user/group, since Lucid's upstart doesn't support `setuid`/`setgid`.

**Comment by hashbrowncipher** [comment]
Closed by #10.
